### ISSUE TITLE
Crash when using unarmed attack as Hellspawn

### ISSUE THREAD

**Issue by Vivid141** [sisby-folk/origins-minus#12]
**Description:** Upon choosing the Hellspawn origin and punching an enemy, my game immediately crashes. This doesn't happen with Origins on its own, though I'm not sure if this happens with /just/ Origins and Origins Minus (and any other dependencies) or if it's an incompatibility with another mod.

**Crash Log:** https://mclo.gs/NXhwmnW

**Versions:**
- Forge Version: 47.2.0
- Minecraft Version: 1.20.1
- Origins Version: 1.20.1-1.10.0.5
- Origins Minus Version: 2.1.1+1.19.3

**Comment by sisby-folk** [comment]
Origins forge is kind of cooked - could you check if this happens with just origins and minus? Minus is just a datapack at the end of the day, so I'll have to redirect you to the origins repo either way

**Comment by Vivid141** [comment]
It does happen with just origins and minus. Here's the crash log (It's /horribly/ long, apologies), and I'll bring this issue over to the Origins github as well. Thanks for your advice.
https://mclo.gs/GxIsNWS

**Comment by sisby-folk** [comment]
yep, looks like definitely an issue with origins/apoli, so they should be able to help better over there.
