### ISSUE TITLE
Enderian seems unbalanced

### ISSUE THREAD

**Issue by Garbanzo95** [sisby-folk/origins-minus#13]
voidthing seems way underpowered to me, especially comparing it to the original origin. not only is the cooldown on your blink WAY too long to be handy in my opinion, it's range is pitiful.  it also just feels unreliable, getting caught on grass frequently. comparing it to the original enderian, the contrast is quite shocking. comparing it to the wildling race, who has a unlimited instant five block high jump, AND takes no fall damage, AND is faster on land, there's basically no reason, if you're a fan of exploration, to choose anything other than either wildling or dryad. i just don't see why the cooldown on voidthings teleport is so high, when all you need is shears and a couple leaf blocks to have dryad completely outclass it in terms of active ability maneuverability anyway!  
Also, sorry if this isn't the right place to post something like this, it's the only place i could find to leave a comment from your modrinth page, and you guys said you were open to suggestion.

**Comment by sisby-folk** [comment]
design note 4! from the modrinth page:

![Screenshot_20240913-202212](https://github.com/user-attachments/assets/49ac9f2e-8a43-43d7-9107-42e3935d69ce)

if you have a specific suggestion for a change that feels good in isolation, feel free to hit us up!

**Comment by Garbanzo95** [comment]
I just want the cooldown on the warp reduced, and for it to ignore long grass. I get my comment was long and rambly, sorry about that, and thank you for your hasty reply.
