### ISSUE TITLE
Dryad Slingshot doesn't work

### ISSUE THREAD

**Issue by MaddieAwesome** [sisby-folk/origins-minus#17]
The Slingshot Dryad is supposed to have (or Vine Whip) does not work, it still plays the particle effects but the player isn't moved. Unsure if maybe it's a weird bug on 1.20.1 Forge, or I'm just not doing something correctly.

Tried it on tree leaves and plants and nothing seems to work besides the particle effects unfortunately :(

**Comment by Xraveler** [comment]
There was a new update in the Origins mod, so that might explain these sudden crashes. Downloading the older version (alpha 9) fixes the Origins to work.

**Comment by sisby-folk** [comment]
considering this fixed via a new warning label
