### ISSUE TITLE
Primary abilities on voidthing and dryad not working.

### ISSUE THREAD

**Issue by Linktheh3ro** [sisby-folk/origins-minus#19]
On 1.21.1 version of minecraft with these mods:

![image](https://github.com/user-attachments/assets/192e290d-c031-476d-8eb1-2cf5e1455c4b)

Both dryad and voidthing's primary active ability seem not to work at all. (Vine whip and teleport respectively).

**Comment by Xraveler** [comment]
There was a recent update to the Origins mod, which may explain the sudden crashes. Downloading the previous version (alpha 9) resolves the issues with the Origins mod.

**Comment by Xraveler** [comment]
helping people is useless...

**Comment by sisby-folk** [comment]
considering this fixed via a new warning label
