### ISSUE TITLE
Weaver rappels get stuck when made in water; don't despawn, infinite noise spam

### ISSUE THREAD

**Issue by twilight-sparkle-irl** [sisby-folk/origins-minus#6]
https://github.com/sisby-folk/origins-minus/assets/15254673/118ed3a1-33a1-47c6-a09d-3b5beb3b58f0

User reports that "sometimes when I rappel underwater it just stays there." Forced to `/kill @e[type=snowball,tag=rappel]`.

**Comment by sisby-folk** [comment]
yeah awful, this thing really shouldn't have a lifespan of anything more than 40 ticks - we're not as familiar with the mcfunction that powers this as we'd like to be if we're honest, so feel free to suggest a way to update the [ticker](https://github.com/sisby-folk/origins-minus/blob/1.19/src/main/resources/data/origins_minus/functions/rappel.mcfunction) for expiring.
